# Generated by Django 4.2.20 on 2026-05-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200416_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='浏览次数')),
                ('last_view_time', models.DateTimeField(auto_now=True, verbose_name='最后浏览时间')),
            ],
            options={
                'verbose_name': '用户浏览',
                'verbose_name_plural': '用户浏览',
            },
        ),
        migrations.DeleteModel(
            name='Num',
        ),
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.FileField(default='', max_length=64, upload_to='product_cover', verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='userview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='userview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userview',
            unique_together={('user', 'product')},
        ),
    ]
