# Generated by Django 4.2.20 on 2026-05-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userview_delete_num_product_pic_userview_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='综合得分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '综合评分',
                'verbose_name_plural': '综合评分',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
